# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-05-23 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_auto_20200523_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='county',
            field=models.CharField(max_length=40),
        ),
    ]
