# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-06-01 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_auto_20200523_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='county',
            field=models.CharField(max_length=50),
        ),
    ]
