# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-04-28 10:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='last_bid',
            new_name='auction_duration',
        ),
        migrations.AddField(
            model_name='item',
            name='auction_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='auction_time_start',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='comment_seller',
            field=models.TextField(default='No comment yet'),
        ),
        migrations.AddField(
            model_name='item',
            name='comment_winner',
            field=models.TextField(default='No comment yet'),
        ),
        migrations.AddField(
            model_name='item',
            name='highest_bid_offer',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='highest_bid_user',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
