# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-05-05 01:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_auto_20200428_1003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='auction_duration',
            new_name='auction_duration_time',
        ),
        migrations.RemoveField(
            model_name='item',
            name='auction_time_start',
        ),
        migrations.AddField(
            model_name='item',
            name='auction_end_time',
            field=models.IntegerField(default=0),
        ),
    ]
