# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-05-07 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_auto_20200507_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='auction_duration_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='auction_end_time',
            field=models.IntegerField(default=0),
        ),
    ]
