# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-05-07 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0008_auto_20200507_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='auction_end_time',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='auction_status',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
