# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-05-07 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0012_auto_20200507_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='highest_bid_user',
            field=models.CharField(default='', max_length=200),
        ),
    ]
