# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-05-07 13:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0017_bid_info_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid_info',
            name='title',
        ),
    ]
