# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-05-27 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0019_item_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='buyer_address',
            field=models.CharField(default=0, max_length=30),
        ),
        migrations.AddField(
            model_name='item',
            name='buyer_country',
            field=models.CharField(default=0, max_length=30),
        ),
        migrations.AddField(
            model_name='item',
            name='buyer_name',
            field=models.CharField(default=0, max_length=30),
        ),
        migrations.AddField(
            model_name='item',
            name='buyer_postcode',
            field=models.CharField(default=0, max_length=30),
        ),
        migrations.AddField(
            model_name='item',
            name='buyer_town',
            field=models.CharField(default=0, max_length=30),
        ),
    ]
