# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-06-06 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0021_auto_20200606_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.PositiveIntegerField(default=1, null=True),
        ),
    ]
