# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-06-08 17:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0023_item_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='time',
            new_name='endtime',
        ),
    ]
