# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-10-05 09:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0025_auto_20201002_1018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='timer',
        ),
    ]
