# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-10-05 09:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0026_remove_item_timer'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='timer',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
